import type { GermanyIncomeGroupRow } from './germanyIncomeDistribution';

/**
 * Italy income distribution on the EU-SILC equivalised disposable-income basis.
 *
 * Official anchors: Istat 2024 S80/S20 = 5.1 and Gini = 0.310. Quintile
 * shares and annual averages are modeled to those anchors and a mean
 * equivalised net income of about €24,000. Migration-background, gender,
 * and political-lean splits are analytical estimates because no comparable
 * official per-quintile cross-tab is published for all of those dimensions.
 */
export const ITALY_INCOME_DISTRIBUTION_GROUPS: readonly GermanyIncomeGroupRow[] = [
  {
    id: 'bottom-20',
    label: 'Bottom 20%',
    shortLabel: 'Bottom',
    tier: 'quintile',
    people: 11_787_000,
    households: 5_260_000,
    incomeSharePct: 7.5,
    avgNetIncomeEur: 9_000,
    avgNetIncomeDisplay: '€9,000',
    migrationBackgroundPct: 23,
    menPct: 45,
    womenPct: 55,
    leftWingPct: 60,
    rightWingPct: 40,
    color: '#ef4444',
  },
  {
    id: 'lower-middle-20',
    label: 'Lower-Middle 20%',
    shortLabel: 'Lower-Mid',
    tier: 'quintile',
    people: 11_787_000,
    households: 5_260_000,
    incomeSharePct: 13.5,
    avgNetIncomeEur: 16_200,
    avgNetIncomeDisplay: '€16,200',
    migrationBackgroundPct: 17,
    menPct: 47,
    womenPct: 53,
    leftWingPct: 55,
    rightWingPct: 45,
    color: '#f97316',
  },
  {
    id: 'middle-20',
    label: 'Middle 20%',
    shortLabel: 'Middle',
    tier: 'quintile',
    people: 11_787_000,
    households: 5_260_000,
    incomeSharePct: 17.5,
    avgNetIncomeEur: 21_000,
    avgNetIncomeDisplay: '€21,000',
    migrationBackgroundPct: 12,
    menPct: 49,
    womenPct: 51,
    leftWingPct: 48,
    rightWingPct: 52,
    color: '#eab308',
  },
  {
    id: 'upper-middle-20',
    label: 'Upper-Middle 20%',
    shortLabel: 'Upper-Mid',
    tier: 'quintile',
    people: 11_787_000,
    households: 5_260_000,
    incomeSharePct: 23.3,
    avgNetIncomeEur: 27_960,
    avgNetIncomeDisplay: '€27,960',
    migrationBackgroundPct: 9,
    menPct: 51,
    womenPct: 49,
    leftWingPct: 43,
    rightWingPct: 57,
    color: '#84cc16',
  },
  {
    id: 'top-20',
    label: 'Top 20%',
    shortLabel: 'Top 20%',
    tier: 'quintile',
    people: 11_787_000,
    households: 5_260_000,
    incomeSharePct: 38.2,
    avgNetIncomeEur: 45_840,
    avgNetIncomeDisplay: '€45,840',
    migrationBackgroundPct: 7,
    menPct: 54,
    womenPct: 46,
    leftWingPct: 38,
    rightWingPct: 62,
    color: '#22c55e',
  },
  {
    id: 'top-10',
    label: 'Top 10%',
    shortLabel: 'Top 10%',
    tier: 'top_subset',
    people: 5_894_000,
    households: 2_630_000,
    incomeSharePct: 24.0,
    avgNetIncomeEur: 57_600,
    avgNetIncomeDisplay: '€57,600',
    migrationBackgroundPct: 6,
    menPct: 56,
    womenPct: 44,
    leftWingPct: 35,
    rightWingPct: 65,
    color: '#14b8a6',
  },
  {
    id: 'top-1',
    label: 'Top 1%',
    shortLabel: 'Top 1%',
    tier: 'top_subset',
    people: 589_000,
    households: 263_000,
    incomeSharePct: 6.2,
    avgNetIncomeEur: 148_800,
    avgNetIncomeDisplay: '€148,800+',
    migrationBackgroundPct: 5,
    menPct: 60,
    womenPct: 40,
    leftWingPct: 30,
    rightWingPct: 70,
    color: '#a78bfa',
  },
] as const;

export const ITALY_INCOME_DISTRIBUTION_CAPTION =
  'Seven income groups · ~58.9M people in quintiles (11.8M each) · 2024 equivalised disposable-income anchors: S80/S20 5.1 and Gini 0.310. Quintile shares and incomes are modeled to official Istat totals; migration background, gender, and political lean are analytical estimates.';