import type { StyleSpecification } from 'maplibre-gl';

/**
 * Coastlines are served as static GeoJSON (`scripts/bake-geo-json.mjs` → `public/geo/`)
 * rather than imported, so ~600 KB of coordinates stay out of the JavaScript bundle.
 * MapLibre fetches and caches the URL itself.
 */
const LOCAL_WORLD_LAND = '/geo/world-land.json';

/** Dark recon basemap with OSM 3D buildings — copied from osint MapView. No API key. */
export const RECON_STYLE = {
  version: 8 as const,
  projection: { type: 'globe' as const },
  glyphs: 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',
  // Kill paint/layout transitions — they steal frames while diving into city detail.
  transition: { duration: 0, delay: 0 },
  sources: {
    'local-world-land': {
      type: 'geojson' as const,
      data: LOCAL_WORLD_LAND,
    },
    openmaptiles: {
      type: 'vector' as const,
      url: 'https://tiles.openfreemap.org/planet',
      attribution: '© OpenStreetMap · OpenFreeMap',
    },
    'hillshade-dem': {
      type: 'raster-dem' as const,
      tiles: ['https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png'],
      encoding: 'terrarium' as const,
      tileSize: 256,
      // Cap DEM fetch — city zooms should spend bandwidth on vector buildings, not elevation.
      maxzoom: 12,
      attribution: 'Elevation © AWS Terrain Tiles',
    },
    'terrain-dem': {
      type: 'raster-dem' as const,
      tiles: ['https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png'],
      encoding: 'terrarium' as const,
      tileSize: 256,
      maxzoom: 12,
    },
  },
  layers: [
    { id: 'bg', type: 'background' as const, paint: { 'background-color': '#0b0b0d' } },
    {
      id: 'local-land',
      type: 'fill' as const,
      source: 'local-world-land',
      paint: { 'fill-color': '#28282b' },
    },
    {
      id: 'local-coastline',
      type: 'line' as const,
      source: 'local-world-land',
      paint: {
        'line-color': 'rgba(255,255,255,0.42)',
        'line-width': ['interpolate', ['linear'], ['zoom'], 0, 0.55, 8, 1.15],
      },
    },
    {
      id: 'hillshade',
      type: 'hillshade' as const,
      source: 'hillshade-dem',
      // Drop hillshade once city fabric matters — frees GPU for roads / buildings.
      maxzoom: 12,
      paint: {
        'hillshade-shadow-color': '#000000',
        'hillshade-highlight-color': '#5c5c5c',
        'hillshade-accent-color': '#000000',
        'hillshade-exaggeration': 0.4,
      },
    },
    {
      id: 'water',
      type: 'fill' as const,
      source: 'openmaptiles',
      'source-layer': 'water',
      paint: { 'fill-color': '#0d0d0d' },
    },
    {
      id: 'roads',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 7,
      paint: {
        'line-color': '#3a3a3a',
        'line-width': ['interpolate', ['linear'], ['zoom'], 7, 0.4, 16, 2.4],
      },
    },
    {
      // Brighter motorway / trunk / primary casing once the camera is city-close.
      id: 'roads-major',
      type: 'line' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: [
        'match',
        ['get', 'class'],
        ['motorway', 'trunk', 'primary'],
        true,
        false,
      ] as unknown as boolean,
      paint: {
        'line-color': [
          'match',
          ['get', 'class'],
          'motorway',
          '#6e6e72',
          'trunk',
          '#5c5c60',
          '#4e4e52',
        ] as unknown as string,
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          ['match', ['get', 'class'], 'motorway', 1.1, 'trunk', 0.9, 0.7],
          14,
          ['match', ['get', 'class'], 'motorway', 3.6, 'trunk', 2.8, 2.2],
        ] as unknown as number,
        'line-opacity': ['interpolate', ['linear'], ['zoom'], 8, 0.35, 10, 0.85],
      },
    },
    {
      // Cheap 2D footprints so city fabric reads immediately; 3D extrusions take over at z14.
      id: 'building-footprint',
      type: 'fill' as const,
      source: 'openmaptiles',
      'source-layer': 'building',
      minzoom: 13,
      maxzoom: 14.25,
      paint: {
        'fill-color': '#555555',
        'fill-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0.55, 14, 0.75],
        'fill-antialias': false,
      },
    },
    {
      id: 'building-3d',
      type: 'fill-extrusion' as const,
      source: 'openmaptiles',
      'source-layer': 'building',
      // Raised from 13 → 14: extrusions at mid-city zoom were the main dive-in hitch.
      minzoom: 14,
      paint: {
        'fill-extrusion-color': [
          'interpolate',
          ['linear'],
          ['get', 'render_height'],
          0,
          '#555555',
          80,
          '#888888',
        ],
        'fill-extrusion-height': ['get', 'render_height'],
        'fill-extrusion-base': ['get', 'render_min_height'],
        'fill-extrusion-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          14,
          0.75,
          14.6,
          0.92,
        ],
        // Vertical gradient is a per-fragment cost on dense city meshes.
        'fill-extrusion-vertical-gradient': false,
      },
    },
    {
      // OpenMapTiles aerodrome_label: international+IATA from z8; broader set from z10+.
      id: 'airport',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'aerodrome_label',
      minzoom: 9,
      filter: ['has', 'iata'] as unknown as boolean,
      layout: {
        'icon-image': 'wt-airport',
        'icon-size': ['interpolate', ['linear'], ['zoom'], 9, 0.72, 12, 1] as unknown as number,
        'icon-allow-overlap': false,
        'icon-optional': false,
        'text-field': [
          'step',
          ['zoom'],
          ['get', 'iata'],
          11,
          [
            'concat',
            ['get', 'iata'],
            '\n',
            ['coalesce', ['get', 'name:en'], ['get', 'name']],
          ],
        ] as unknown as string,
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 9, 10, 12, 12],
        'text-anchor': 'top' as const,
        'text-offset': [0, 0.85],
        'text-max-width': 9,
        'text-optional': true,
        'text-padding': 2,
        'symbol-sort-key': [
          'match',
          ['get', 'class'],
          'international',
          1,
          'public',
          2,
          'regional',
          3,
          5,
        ] as unknown as number,
      },
      paint: {
        'icon-opacity': ['interpolate', ['linear'], ['zoom'], 9, 0.55, 10, 1],
        'text-color': '#e6e6e6',
        'text-halo-color': '#000000',
        'text-halo-width': 1.25,
        'text-opacity': ['interpolate', ['linear'], ['zoom'], 9, 0.5, 10.5, 0.95],
      },
    },
    {
      // Motorway / trunk / primary route shields — ref text on a monochrome plate.
      id: 'highway-shield',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation_name',
      minzoom: 11,
      filter: [
        'all',
        ['has', 'ref'],
        ['<=', ['coalesce', ['get', 'ref_length'], 99], 6],
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['match', ['get', 'class'], ['motorway', 'trunk', 'primary'], true, false],
      ] as unknown as boolean,
      layout: {
        'icon-image': ['concat', 'wt-road-', ['to-string', ['get', 'ref_length']]] as unknown as string,
        'icon-size': 1,
        'icon-rotation-alignment': 'viewport' as const,
        'symbol-placement': [
          'step',
          ['zoom'],
          'point',
          12,
          'line',
        ] as unknown as 'point',
        'symbol-spacing': 280,
        'text-field': ['to-string', ['get', 'ref']] as unknown as string,
        'text-font': ['Noto Sans Bold'],
        'text-size': 10,
        'text-rotation-alignment': 'viewport' as const,
        'text-letter-spacing': 0.02,
        'icon-padding': 2,
        'text-padding': 2,
      },
      paint: {
        'icon-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          ['match', ['get', 'class'], 'motorway', 0.85, 'trunk', 0.55, 0],
          12,
          ['match', ['get', 'class'], 'motorway', 1, 'trunk', 0.9, 0.75],
        ] as unknown as number,
        'text-color': '#f0f0f0',
        'text-halo-color': 'rgba(0,0,0,0.85)',
        'text-halo-width': 0.6,
        'text-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          ['match', ['get', 'class'], 'motorway', 0.85, 'trunk', 0.55, 0],
          12,
          ['match', ['get', 'class'], 'motorway', 1, 'trunk', 0.9, 0.75],
        ] as unknown as number,
      },
    },
    {
      id: 'label-street',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'transportation_name',
      minzoom: 14,
      layout: {
        'symbol-placement': 'line' as const,
        'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']] as unknown as string,
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 14, 9, 18, 13],
        'text-max-angle': 30,
        'symbol-spacing': 280,
      },
      paint: {
        'text-color': '#cbcbcb',
        'text-halo-color': '#000000',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'label-place-minor',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: [
        'match',
        ['get', 'class'],
        ['suburb', 'neighbourhood', 'quarter', 'hamlet', 'village', 'island'],
        true,
        false,
      ] as unknown as boolean,
      minzoom: 12,
      layout: {
        'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']] as unknown as string,
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 12, 10, 16, 15],
        'text-max-width': 8,
        'symbol-sort-key': ['coalesce', ['get', 'rank'], 20] as unknown as number,
      },
      paint: {
        'text-color': '#bdbdbd',
        'text-halo-color': '#000000',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'label-place-city',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['match', ['get', 'class'], ['city', 'town'], true, false] as unknown as boolean,
      minzoom: 3,
      maxzoom: 15,
      layout: {
        'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']] as unknown as string,
        'text-font': ['Noto Sans Regular'],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          ['case', ['<=', ['coalesce', ['get', 'rank'], 10], 2], 12, 0],
          7,
          ['case', ['<=', ['coalesce', ['get', 'rank'], 10], 6], 14, 11],
          12,
          ['case', ['<=', ['coalesce', ['get', 'rank'], 10], 6], 19, 15],
        ] as unknown as number,
        'text-max-width': 8,
        'symbol-sort-key': ['coalesce', ['get', 'rank'], 10] as unknown as number,
      },
      paint: {
        'text-color': '#ededed',
        'text-halo-color': '#000000',
        'text-halo-width': 1.3,
      },
    },
    {
      id: 'label-state',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', ['get', 'class'], 'state'] as unknown as boolean,
      minzoom: 3,
      maxzoom: 9,
      layout: {
        'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']] as unknown as string,
        'text-font': ['Noto Sans Regular'],
        'text-transform': 'uppercase' as const,
        'text-letter-spacing': 0.1,
        'text-size': ['interpolate', ['linear'], ['zoom'], 3, 10, 6, 13, 9, 15],
        'text-max-width': 8,
      },
      paint: {
        'text-color': '#9a9a9a',
        'text-halo-color': '#000000',
        'text-halo-width': 1.2,
        'text-opacity': ['interpolate', ['linear'], ['zoom'], 3, 0, 4, 0.9, 7.5, 0.9, 9, 0],
      },
    },
    {
      id: 'label-country',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', ['get', 'class'], 'country'] as unknown as boolean,
      maxzoom: 9,
      layout: {
        'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']] as unknown as string,
        'text-font': ['Noto Sans Bold'],
        'text-transform': 'uppercase' as const,
        'text-letter-spacing': 0.14,
        'text-size': ['interpolate', ['linear'], ['zoom'], 1, 9, 4, 14, 7, 18],
        'text-max-width': 7,
        'symbol-sort-key': ['coalesce', ['get', 'rank'], 5] as unknown as number,
      },
      paint: {
        'text-color': '#f4f4f4',
        'text-halo-color': '#000000',
        'text-halo-width': 1.5,
        'text-opacity': ['interpolate', ['linear'], ['zoom'], 1, 0.75, 3, 1, 6.5, 1, 9, 0],
      },
    },
    {
      id: 'label-water',
      type: 'symbol' as const,
      source: 'openmaptiles',
      'source-layer': 'water_name',
      layout: {
        'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']] as unknown as string,
        'text-font': ['Noto Sans Italic'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 2, 10, 8, 14],
        'text-max-width': 8,
        'symbol-placement': 'point' as const,
      },
      paint: {
        'text-color': '#5f6b78',
        'text-halo-color': '#000000',
        'text-halo-width': 1,
      },
    },
  ],
} as unknown as StyleSpecification;
