import type { GermanyLaborCsvRow } from '../germany/germanyLaborStatistics';

export const FRANCE_LABOR_STATISTICS_ROWS: readonly GermanyLaborCsvRow[] = [
  {
    country: 'France',
    metric: 'Youth unemployment rate',
    submetric: '',
    breakdown: 'Ages 15–24',
    value: '21.1',
    unit: 'percent',
    referenceYear: '2026 Q1',
    sourceName: '',
    sourceUrl: '',
    notes: '',
  },
  {
    country: 'France',
    metric: 'Labour force participation rate',
    submetric: '',
    breakdown: 'Overall',
    value: '74.4',
    unit: 'percent',
    referenceYear: '2024',
    sourceName: '',
    sourceUrl: '',
    notes: '',
  },
  {
    country: 'France',
    metric: 'Labour force participation rate',
    submetric: 'By immigrant status',
    breakdown: 'Non-immigrants',
    value: '75.0',
    unit: 'percent',
    referenceYear: '2024',
    sourceName: '',
    sourceUrl: '',
    notes: '',
  },
  {
    country: 'France',
    metric: 'Labour force participation rate',
    submetric: 'By immigrant status',
    breakdown: 'Immigrants',
    value: '70.6',
    unit: 'percent',
    referenceYear: '2024',
    sourceName: '',
    sourceUrl: '',
    notes: '',
  },
  {
    country: 'France',
    metric: 'Labour force participation rate',
    submetric: 'By immigrant status',
    breakdown: 'Immigrants outside EU-27',
    value: '69.9',
    unit: 'percent',
    referenceYear: '2024',
    sourceName: '',
    sourceUrl: '',
    notes: '',
  },
  {
    country: 'France',
    metric: 'Labour force participation rate',
    submetric: 'By immigrant status',
    breakdown: 'Immigrants from EU-27',
    value: '74.0',
    unit: 'percent',
    referenceYear: '2024',
    sourceName: '',
    sourceUrl: '',
    notes: '',
  },
  {
    country: 'France',
    metric: 'Minimum wage',
    submetric: '',
    breakdown: '',
    value: '€11.88',
    unit: 'gross per hour',
    referenceYear: '2025',
    sourceName: '',
    sourceUrl: '',
    notes: '',
  },
  {
    country: 'France',
    metric: 'Long-term unemployment rate',
    submetric: '',
    breakdown: '',
    value: '1.8',
    unit: 'percent',
    referenceYear: '2025',
    sourceName: '',
    sourceUrl: '',
    notes: '% of labour force aged 15-74',
  },
  {
    country: 'France',
    metric: 'Average annual working hours per worker',
    submetric: '',
    breakdown: '',
    value: '≈1,500',
    unit: 'hours per employed worker',
    referenceYear: '2025',
    sourceName: '',
    sourceUrl: '',
    notes: '',
  },
] as const;
